### PR TITLE
Map game id 21 with input, button and comments

### PR DESCRIPTION
**Pull request by anniavdc**
Hi @patrozada can you check this? @ioanadamo and have filtered and maped just the game with id 21.

### CODE REVIEW

**Review by patrozada — CHANGES_REQUESTED** [review]
Hi @anniavdc,
the mapping and the filter are working correctly, I can see only game 21 rendered, but when I try to send a message I get the following error:
```
TypeError: Cannot read property 'id' of undefined
Game.handleButtonClick
src/components/Game.js:13
```
Let me know if you need anything else.

**Comment by anniavdc** [comment]
Hi @patrozada you are right we've check it and fix it. Can you check it?

**Comment by patrozada** [comment]
@anniavdc,
now it's working. the only thing is that the message stays in the text area when you push send, and it seems like it not working. Maybe we can improve this?

**Review by patrozada — APPROVED** [review]
Appart from the suggestions in the comment before, I think this is ready to merge :)

**Pull request merged**
