### PR TITLE
Header

### PR DESCRIPTION
**Pull request by ioanadamo**
Hello @anniavdc i added the styles for the header component.
Could you please review it and let me know if it's ok to merge?
Thank you.

### CODE REVIEW

**Comment by anniavdc** [comment]
Hi @ioanadamo can you add a background-position: center?

**Comment by ioanadamo** [comment]
@anniavdc added the background-position: center to the hero image. 
Could you please review it?
Thank you,

**Comment by anniavdc** [comment]
Looks good, you can merge

**Review by anniavdc — APPROVED** [review]
The conflicts were solved in github.

**Pull request merged**
